version: '3.8'

services:
  postgres-authuser:
    image: postgres:15-alpine
    container_name: postgres-authuser
    environment:
      POSTGRES_DB: ead-authuser
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
    ports:
      - "5432:5432"
    volumes:
      - postgres_authuser_data:/var/lib/postgresql/data
    networks:
      - authuser-network

  rabbitmq-authuser:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-authuser
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - authuser-network

volumes:
  postgres_authuser_data:

networks:
  authuser-network:
    driver: bridge