server:
  port: 8080

spring:
  application:
    name: ead-api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      routes:
        - id: authuser-service
          uri: lb://ead-authuser-service
          predicates:
            - Path=/ead-authuser/**
        - id: course-service
          uri: lb://ead-course-service
          predicates:
            - Path=/ead-course/**
        - id: notification-service
          uri: lb://ead-notification-service
          predicates:
            - Path=/ead-notification/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost